version: '3.8'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    container_name: es
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  # kibana:
  #   depends_on:
  #     - elasticsearch
  #   image: docker.elastic.co/kibana/kibana:8.1.0
  #   container_name: kibana
  #   volumes:
  #     - kibana-data:/usr/share/kibana/data
  #   ports:
  #    - 5601:5601
  #   restart: always
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  fastapi:
    build: ./
    depends_on:
      - es
    ports:
      - 8000:8000
    restart: always
volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local